name: scanned
description: Flutter plugin for scan barcode an QR in iOS and Android.
version: 0.0.2+1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.shrapp.scanned
        pluginClass: ScanPlugin
      ios:
        pluginClass: ScannedPlugin
  assets:
    - assets/logo.png